# Somatic deletion/duplication for HCC2218 breast cancer cell lines
# https://github.com/Illumina/Canvas#demo-tumor-normal-enrichment-workflow 
---
upload:
  dir: ../final
details:
  - files: [../input/HCC2218BL_S1.bam]
    description: HCC2218BL
    metadata:
      batch: HCC2218
      phenotype: normal
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      save_diskspace: true
      variantcaller: 
        germline: [freebayes]
        somatic: [vardict]
      svcaller: [cnvkit, seq2c, manta, delly, lumpy, wham, gridss, titancna]
      vcfanno: [gemini]
      tools_off: [vqsr]
      variant_regions: ../input/NexteraRapidCapture_Exome_TargetedRegions_v1.2Used.bed.gz
  - files: [../input/HCC2218C_S1.bam]
    description: HCC2218C
    metadata:
      batch: HCC2218
      phenotype: tumor
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      save_diskspace: true
      variantcaller: 
        germline: [freebayes]
        somatic: [vardict]
      svcaller: [cnvkit, seq2c, manta, delly, lumpy, wham, gridss, titancna]
      vcfanno: [gemini]
      tools_off: [vqsr]
      svvalidate: ../input/HCC2218Truth-clean-prep.vcf.gz
      variant_regions: ../input/NexteraRapidCapture_Exome_TargetedRegions_v1.2Used.bed.gz
